baseURL = "https://sschuepbach.github.io/metamorph-hacks/"
languageCode = "de-ch"
title = "Metamorph Hacks"
theme = "kraiklyn"

publishDir = "docs"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "Metamorph Hacks"
sidebarColor = "default"
customCss = []
