baseURL = "https://swissbib.gitlab.io/metamorph-doku"

languageCode = "de-ch"
DefaultContentLanguage = "de"
title = "Metamorph Hacks"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

publishDir = "public/"

defaultContentLanguage = "de"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
editURL = "https://github.com/sschuepbach/metamorph-hacks/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Code</label>"
identifier = "ds"
url = "https://github.com/sschuepbach/metamorph-hacks"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> <label>Metafacture code</label>"
url = "https://github.com/metafacture/metafacture-core"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>Metafacture wiki</label>"
url = "https://github.com/metafacture/metafacture-core/wiki/"
weight = 20
